//
//  BrandWorker.swift
//  iOSTestFirebase
//
//  Created by Makrem chambah on 11/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation
import Promise

class BrandWorker
{
  func doSomeWork()
  {
  }
    
    func loadBrands() -> Promise<[NSDictionary]> {
        return BrandAPI.loadBrands()
    }
}
