//
//  BrandPresenter.swift
//  iOSTestFirebase
//
//  Created by Makrem chambah on 11/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BrandPresentationLogic
{
  func presentSomething(response: Brand.Something.Response)
    func successGettingBrands(response:[NSDictionary])
}

class BrandPresenter: BrandPresentationLogic
{
    
    
  weak var viewController: BrandDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Brand.Something.Response)
  {
    let viewModel = Brand.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    
    func successGettingBrands(response: [NSDictionary]) {
        viewController?.loadData(response:response)
    }
}
