//
//  BrandDetailsPresenter.swift
//  iOSTestFirebase
//
//  Created by Makrem chambah on 11/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BrandDetailsPresentationLogic
{
    func presentSomething(response: BrandDetails.Something.Response)
    func successGettingPurchases(response:[NSDictionary])
}

class BrandDetailsPresenter: BrandDetailsPresentationLogic
{
    
    
    weak var viewController: BrandDetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: BrandDetails.Something.Response)
    {
        let viewModel = BrandDetails.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func successGettingPurchases(response:[NSDictionary]){
        viewController?.displayData(response:response)
    }
}
