//
//  BrandDetailsViewController.swift
//  iOSTestFirebase
//
//  Created by Makrem chambah on 11/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher
import Foundation

protocol BrandDetailsDisplayLogic: class
{
    func displaySomething(viewModel: BrandDetails.Something.ViewModel)
    func displayData(response:[NSDictionary])
}

class BrandDetailsViewController: UIViewController, BrandDetailsDisplayLogic
{
    //    MARK:- Outlets declarations :
    @IBOutlet weak var brandImageView     : UIImageView!
    @IBOutlet weak var descriptionLabel   : UILabel!
    
    
    //    MARK:- var declarations:
    var interactor      : BrandDetailsBusinessLogic?
    var router          : (NSObjectProtocol & BrandDetailsRoutingLogic & BrandDetailsDataPassing)?
    var content         : NSDictionary = [:]
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor            = BrandDetailsInteractor()
        let presenter             = BrandDetailsPresenter()
        let router                = BrandDetailsRouter()
        viewController.interactor = interactor
        viewController.router     = router
        interactor.presenter      = presenter
        presenter.viewController  = viewController
        router.viewController     = viewController
        router.dataStore          = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        self.title =  ((content["name"])! as! String)
        displayElements()
        designForImageBrand()
        let id : String = content["offerId"]! as! String
        print(content["offerId"]!)
        self.interactor?.loadPurchases(id : id)
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = BrandDetails.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: BrandDetails.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    var commission : String = ""
    func displayElements(){
        self.descriptionLabel.text = (self.content["description"] as! String)
        let url = URL(string: (self.content["pic"])! as! String)
        self.brandImageView.kf.setImage(with: url!,
                                        options: [.onlyLoadFirstFrame], completionHandler: {
                                            result in
                                            switch result {
                                            case .success:
                                                print(result)
                                                break
                                            case .failure:
                                                self.brandImageView.image = UIImage(named: "noImg")!
                                            }
                                        })
    }
    
    func designForImageBrand(){
        self.brandImageView.layer.cornerRadius        = 10
        self.brandImageView.layer.shadowColor         = UIColor.systemGray5.cgColor
        self.brandImageView.layer.shadowOffset        = .zero
        self.brandImageView.layer.shadowRadius        = 10
        self.brandImageView.layer.shadowPath          = UIBezierPath(rect: self.brandImageView.bounds).cgPath
        self.brandImageView.backgroundColor           = UIColor.white
        self.brandImageView.layer.shadowOpacity       = 1
        self.brandImageView.layer.shouldRasterize     = true
        self.brandImageView.layer.rasterizationScale  = UIScreen.main.scale
    }
    
    func displayData(response:[NSDictionary]){
        print(response)
    }
}
