//
//  ArticlesPresenter.swift
//  testiOSFireBase
//
//  Created by Makrem chambah on 10/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticlesPresentationLogic
{
    func presentSomething(response: Articles.Something.Response)
    func successGettingArticles(response:[NSDictionary])
    func gettingArticlesFailure(response: [NSDictionary])
}

class ArticlesPresenter: ArticlesPresentationLogic
{
    weak var viewController: ArticlesDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Articles.Something.Response)
    {
        let viewModel = Articles.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func successGettingArticles(response:[NSDictionary]){
        viewController?.displayData(response:response)
    }
    
    func gettingArticlesFailure(response: [NSDictionary]){
        viewController?.displayDataFailure(response: response)
    }
}
