//
//  ArticlesInteractor.swift
//  testiOSFireBase
//
//  Created by Makrem chambah on 10/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticlesBusinessLogic
{
    func doSomething(request: Articles.Something.Request)
    func loadArticles()
}

protocol ArticlesDataStore
{
    //var name: String { get set }
}

class ArticlesInteractor: ArticlesBusinessLogic, ArticlesDataStore
{
    var presenter: ArticlesPresentationLogic?
    var worker: ArticlesWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Articles.Something.Request)
    {
        worker = ArticlesWorker()
        worker?.doSomeWork()
        
        let response = Articles.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    
    func loadArticles(){
        worker = ArticlesWorker()
        worker?.loadArticles().then(){
            response in
            print(response)
            self.presenter!.successGettingArticles(response:response)
        }.catch{ error in
            print(error)
            let error : [NSDictionary] = []
            self.presenter!.gettingArticlesFailure(response: error)
        }
    }
}
